spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://157.230.42.125:3306/myicellar?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Test#123
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoint:
    health:
      show-details: always

file-upload:
  base-url: http://157.230.42.125:8088/digital-winemenu-web
  base-path: /var/app1/imagedata/
  image:
    ext-names: jpg,png,gif,tif,bmp
    max-height: 3000
    max-width: 3000
    max-size: 5242880
    small-height: 100
    small-width: 0
  attachment:
    ext-names: jpg,png,jpeg,doc,docx,xlsx,xls,pdf,zip,rar
    max-size: 10485760